### ISSUE TITLE
git status -s中M的显示问题

### ISSUE THREAD

**Issue by xujiangjun** [suzeyu1992/GitOperateDemo#3]
Mac下M 字母都是出现在左边，只是用红绿色标识，红色表示修改未暂存，绿色表示修改已暂存，Windows未做测试。

**Comment by suzeyu1992** [comment]
Hi,   你可以这样做来复现出两个M的标识:

1. 首先对一个文件进行了修改, 此时是红色M
2. 然后对这个文件进行add操作, 此时是绿色M
3. 继续修改这一下这个文件,  此时就会两个M, 分别是左绿又红,代表着此文件一部分修改添加到暂存区, 一部分仍然是工作区
